### ISSUE TITLE
Running this in 2023?

### ISSUE THREAD

**Issue by jansdhillon** [roboflow-ai/RoboflowExpoExample#5]
Hello,

I am trying to run this example app in 2023 but I am having some issues getting it to run in 2023. I changed the Roboflow source from your roboflow-ai (404) to just roboflow and pod install ran okay. However, I am running XCode 15 and iOS 17 and I keep getting "Command PhaseScriptExecution failed with a nonzero exit code." I tried downgrading my Node version (from 20 to 16) but that didn't seem to work. Is this still a supported package?

**Comment by jansdhillon** [comment]
Specifically, I am getting this error in XCode:

error Cannot read properties of undefined (reading 'transformFile').
TypeError: Cannot read properties of undefined (reading 'transformFile')
    at /Users/imigh/Coding/COSC448/Recycling/RoboflowExpoExample/node_modules/metro/src/Bundler.js:95:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/imigh/Coding/COSC448/Recycling/RoboflowExpoExample/node_modules/metro/src/Bundler.js:14:24)
    at _next (/Users/imigh/Coding/COSC448/Recycling/RoboflowExpoExample/node_modules/metro/src/Bundler.js:36:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
info Run CLI with --verbose flag for more details.
Command PhaseScriptExecution failed with a nonzero exit code
